-- auto Generated on 2019-04-30
-- DROP TABLE IF EXISTS `resource`;
CREATE TABLE `resource`(
	`id` BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`level` INT (11) NOT NULL DEFAULT -1 COMMENT '等级 1-一级菜单 2-二级菜单 3-按钮',
	`parent_id` BIGINT (15) NOT NULL DEFAULT -1 COMMENT '',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '名称',
	`action_id` BIGINT (15) NOT NULL DEFAULT -1 COMMENT '请求资源id',
	`code` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '编码',
	`icon` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '图标',
	`url` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '链接',
	`sort` INT (11) NOT NULL DEFAULT -1 COMMENT '排序',
	`display_icon` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '展示图标',
	`is_deleted` INT (11) NOT NULL DEFAULT -1 COMMENT '是否删除 0-未删除 1-已删除',
	`create_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '`resource`';
