-- auto Generated on 2019-04-30
-- DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`(
	`id` BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '角色编号',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '名称',
	`created` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '创建日期',
	`updated` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '更新日期',
	`is_deleted` INT (11) NOT NULL DEFAULT -1 COMMENT '删除标记',
	PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '`roles`';
