spring:
  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  # 缓存
  redis:
    database: 0
    host: 127.0.01
    port: 7004
    password: root
    pool:
      max-active: 200
      max-idle: 20
      max-wait: -1
      min-idle: 2
    timeout: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml