package com.mmall.mmallproduct.mapper;

import com.mmall.mmallproduct.pojo.model.Product;
import com.mmall.mmallproduct.pojo.param.ProductParam;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * @author Think
 */
@Mapper
public interface ProductMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @param record Product
     * @return int
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @param id Product
     * @return Product
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @param record Product
     * @return int
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @param record Product
     * @return int
     */
    int updateByPrimaryKeyWithBLOBs(Product record);

    /**
     * 分页列表
     *
     * @param productParam ProductParam
     * @return Product
     */
    List<Product> list(ProductParam productParam);
}